//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoiDongChamThi
    {
        public int ID { get; set; }
        public int LuanVanID { get; set; }
        public int GiangVienID { get; set; }
        public Nullable<int> Diem { get; set; }
        public string NhanXet { get; set; }

        public HoiDongChamThi() { }
        public HoiDongChamThi(int iD, int luanVanID, int giangVienID, int? diem, string nhanXet)
        {
            ID = iD;
            LuanVanID = luanVanID;
            GiangVienID = giangVienID;
            Diem = diem;
            NhanXet = nhanXet;
        }

    }
}
