//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class LuanVan
    {
        public int ID { get; set; }
        public string TieuDe { get; set; }
        public string MoTa { get; set; }
        public string ChucNang { get; set; }
        public string YeuCau { get; set; }
        public int SoLuongSinhVien { get; set; }
        public string TheLoai { get; set; }
        public string CongNghe { get; set; }
        public int GiangVienID { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<int> Diem { get; set; }

        public LuanVan() { }
        public LuanVan(int iD, string tieuDe, string moTa, string chucNang, string yeuCau, int soLuongSinhVien, string theLoai, string congNghe, int giangVienID, string tinhTrang, int? diem)
        {
            ID = iD;
            TieuDe = tieuDe;
            MoTa = moTa;
            ChucNang = chucNang;
            YeuCau = yeuCau;
            SoLuongSinhVien = soLuongSinhVien;
            TheLoai = theLoai;
            CongNghe = congNghe;
            GiangVienID = giangVienID;
            TinhTrang = tinhTrang;
            Diem = diem;
        }

    }
}
