//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class LyDo
    {
        public int ID { get; set; }
        public Nullable<int> LuanVanID { get; set; }
        public Nullable<int> SinhVienID { get; set; }
        public string LyDoText { get; set; }

        public LyDo() { }
        public LyDo(int iD, int? luanVanID, int? sinhVienID, string lyDoText)
        {
            ID = iD;
            LuanVanID = luanVanID;
            SinhVienID = sinhVienID;
            LyDoText = lyDoText;
        }

    }
}
