//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhiemVu
    {
        public int ID { get; set; }
        public string TieuDe { get; set; }
        public string MoTa { get; set; }
        public System.DateTime ThoiGianDenHan { get; set; }
        public Nullable<int> TiLePhanCham { get; set; }
        public int LuanVanID { get; set; }
        public int TacGiaID { get; set; }
        public Nullable<int> NguoiDuocGiao { get; set; }
        public string BaiNop { get; set; }
        public bool HoanThanh { get; set; }

        public NhiemVu() { }
        public NhiemVu(int iD, string tieuDe, string moTa, DateTime thoiGianDenHan, int? tiLePhanCham, int luanVanID, int tacGiaID, int? nguoiDuocGiao, string baiNop, bool hoanThanh)
        {
            ID = iD;
            TieuDe = tieuDe;
            MoTa = moTa;
            ThoiGianDenHan = thoiGianDenHan;
            TiLePhanCham = tiLePhanCham;
            LuanVanID = luanVanID;
            TacGiaID = tacGiaID;
            NguoiDuocGiao = nguoiDuocGiao;
            BaiNop = baiNop;
            HoanThanh = hoanThanh;
        }

    }
}
