//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhiemVu_TroChuyen
    {
       
        public int ID { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<int> NhiemVuID { get; set; }
        public int NguoiGiu { get; set; }

        public NhiemVu_TroChuyen()
        {
        }

        public NhiemVu_TroChuyen(int id, string noiDung, DateTime? thoiGian, int? nhiemVuID, int nguoiGiu)
        {
            ID = id;
            NoiDung = noiDung;
            ThoiGian = thoiGian;
            NhiemVuID = nhiemVuID;
            NguoiGiu = nguoiGiu;
        }

    }
}
