//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nhom
    {

        public int ID { get; set; }
        public int LuanVanID { get; set; }
        public int ThanhVienID { get; set; }
        public Nullable<int> TiLeHoanThanh { get; set; }
        public Nullable<double> Diem { get; set; }

        public Nhom() { }
        public Nhom(int iD, int luanVanID, int thanhVienID, int? tiLeHoanThanh, double? diem)
        {
            ID = iD;
            LuanVanID = luanVanID;
            ThanhVienID = thanhVienID;
            TiLeHoanThanh = tiLeHoanThanh;
            Diem = diem;
        }

    }
}
