//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongBao
    {
        public int ID { get; set; }
        public int NguoiDungID { get; set; }
        public string NoiDung { get; set; }
        public System.DateTime ThoiGian { get; set; }
        public bool DaDoc { get; set; }
        public string TheLoai { get; set; }
        public string TieuDe { get; set; }
        public int ThongTinThem { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }

        public ThongBao() { }
        public ThongBao(int iD, int nguoiDungID, string noiDung, DateTime thoiGian, bool daDoc, string theLoai, string tieuDe, int thongTinThem)
        {
            ID = iD;
            NguoiDungID = nguoiDungID;
            NoiDung = noiDung;
            ThoiGian = thoiGian;
            DaDoc = daDoc;
            TheLoai = theLoai;
            TieuDe = tieuDe;
            ThongTinThem = thongTinThem;
        }

    }
}
